sudo: required
dist: trusty

language: cpp

compiler:
    - gcc
    - clang

install:
    # Install clang c++ std library
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install libc++-dev -y; fi

    # Install all the dependencies
    - sudo apt-get install libsfml-dev -y
    - sudo apt-get install libpugixml-dev -y
    - sudo apt-get install zlib1g-dev -y

script: cmake . && make
