language: cpp
compiler:
    - gcc
    - clang

before_install:
    # GCC 4.8.1 repository
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # SFML repository
    - sudo add-apt-repository -y ppa:sonkun/sfml

    - sudo apt-get update

install:
    # Install g++ 4.8
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

    # Install SFML
    - sudo apt-get install libsfml-dev

    # Install pugixml
    # - sudo apt-get install libpugixml-dev

    # Install zlib
    - sudo apt-get install zlib1g-dev

script: cmake . && make
